[package]
name = "cs5600-project"
version = "0.1.0"
authors = ["Jeffrey Meyer <itotallyrock>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
